services:
  # Serviço simples para desenvolvimento
  queue-sdk-dev:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: queue-sdk-dev
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: /bin/bash

networks:
  default:
    name: queue-sdk-network
